name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 5 * * *' # run at 5 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      run: sudo apt-get install mesa-common-dev libsdl2-dev liblua5.3-dev libgtk-3-dev

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.2.3
      with:
        version: master
    
    - name: Build Workbench
      run: |
        zig build
