name: Continuous Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 5 * * *' # run at 5 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      run: sudo apt-get install mesa-common-dev libsdl2-dev liblua5.3-dev libgtk-3-dev

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.2.3
      with:
        version: master
    
    - name: Build Workbench (Linux, GNU)
      run: |
        zig build -Dtarget=x86_64-native-gnu

    - name: Upload artifact (Linux, GNU)
      uses: actions/upload-artifact@v2
      with:
        name: workbench-linux
        path: |
          zig-cache/bin/cg-workbench
          icons/*
    
    # - name: Build Workbench (Win32)
    #   run: |
    #     zig build -Dtarget=i386-windows-gnu
    # 
    # - name: Upload artifact (Win32)
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: workbench-win32
    #     path: |
    #       zig-cache/bin/cg-workbench.exe
    #       lib/SDL2-2.0.12.mingw/i686-w64-mingw32/bin/SDL2.dll
    #       icons/*
    
    - name: Build Workbench (Win64)
      run: |
        zig build -Dtarget=x86_64-windows-gnu
    
    - name: Upload artifact (Win64)
      uses: actions/upload-artifact@v2
      with:
        name: workbench-win64
        path: |
          zig-cache/bin/cg-workbench.exe
          lib/SDL2-2.0.12.mingw/x86_64-w64-mingw32/bin/SDL2.dll
          icons/*