name: Continuous Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 5 * * *' # run at 5 AM UTC

jobs:
  linux-64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      run: sudo apt-get install mesa-common-dev libsdl2-dev liblua5.3-dev libgtk-3-dev

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.2.3
      with:
        version: master
    
    - name: Build Workbench (Linux, GNU)
      run: |
        zig build -Dtarget=x86_64-native-gnu -Drelease-safe -Dstrip

    - name: Upload artifact (Linux, GNU)
      uses: actions/upload-artifact@v2
      with:
        name: workbench-linux
        path: |
          zig-cache/bin/cg-workbench
          icons/*
    
  win64-64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      run: sudo apt-get install mesa-common-dev libsdl2-dev liblua5.3-dev libgtk-3-dev

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.2.3
      with:
        version: master
    
    - name: Build Workbench (Win64)
      run: |
        zig build -Dtarget=x86_64-windows-gnu -Dstrip
      # https://github.com/MasterQ32/cg-workbench/issues/7: -Drelease-safe 
    
    - name: Upload artifact (Win64)
      uses: actions/upload-artifact@v2
      with:
        name: workbench-win64
        path: |
          zig-cache/bin/cg-workbench.exe

# https://github.com/MasterQ32/cg-workbench/issues/1
#  win-32:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#      with:
#        submodules: 'recursive'
#    
#    - name: Install dependencies
#      run: sudo apt-get install mesa-common-dev libsdl2-dev liblua5.3-dev libgtk-3-dev
#
#    - name: Setup Zig
#      uses: goto-bus-stop/setup-zig@v1.2.3
#      with:
#        version: master
#    
#    - name: Build Workbench (Win32)
#      run: |
#        zig build -Dtarget=i386-windows-gnu -Dstrip
#      # https://github.com/MasterQ32/cg-workbench/issues/7: -Drelease-safe 
#    
#    - name: Upload artifact (Win32)
#      uses: actions/upload-artifact@v2
#      with:
#        name: workbench-win32
#        path: |
#          zig-cache/bin/cg-workbench.exe
